# -*- coding: utf-8 -*-
"""oibsip_taskno_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pJMa73oL5U1QrcHHDIwCyvymy-L1-kC2

**Task 1** : IRIS FLOWER CLASSIFICATION
"""

from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Target variable

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()

clf.fit(X_train, y_train)

from sklearn.metrics import accuracy_score
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

new_measurements = [[5.1, 3.5, 1.4, 0.2]]  # Replace with your measurements
predicted_species = clf.predict(new_measurements)
print(f"Predicted Species: {iris.target_names[predicted_species][0]}")

from joblib import dump
dump(clf, 'iris_model.joblib')