# -*- coding: utf-8 -*-
"""oibsip_taskno_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pivWKLCUEBOdanBH3kvJZMqvCmQRzSyU

**Task 2: UNEMPLOYMENT ANALYSIS WITH PYTHON**
"""

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
data=pd.read_csv('/content/Unemployment in India.csv')
data=pd.read_csv('/content/Unemployment_Rate_upto_11_2020.csv')

# Data Exploration
print(data.head())  # Inspect the first few rows
print(data.info())  # Get data summary

# Data Cleaning
# Handle missing values and outliers as needed

# Data Visualization
plt.figure(figsize=(12, 6))
data.columns=['States','Date','Frequency','Estimated Unemployment rate','Estimated Employed','Estimated Labour participation rate','Region','Longitude','Latitude']
plt.title('Unemployment Rate Over Time')
sns.histplot(x='Estimated Employed',hue='Region',data=data)
plt.ylabel('Frequency')
plt.xlabel('Unemployment Rate')
plt.show()